### ISSUE TITLE
Why don't you directly use Phi-score instead of Zen-score?

### ISSUE THREAD

**Issue by TheSunWillRise** [idstcv/ZenNAS#10]
As I understand, the proposed Zen-score is an approximation of Phi-score for searching models with BN. If so, **why don't you firstly use Phi-score to search an architecture without BN, then add BN layers to it?**

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！
