### ISSUE TITLE
Pretrained Zennets and Evolution Search Algorithm

### ISSUE THREAD

**Issue by silver-deguz** [idstcv/ZenNAS#11]
Hi, interesting work!

I had a couple of clarifying questions regarding the evolution search and the models provided.

For the pretrained models, those were trained on a V100 if I understood the paper correctly? 

The inference speed charts on the T4 and Pixel 2 are only from exporting to TensorRT rather than actually training on the T4 and Pixel 2?

**Comment by MingLin-home** [comment]
Hi Silver,

Thank you for your interest in our work!

Q1:  those were trained on a V100 if I understood the paper correctly?
A1: Yes.

Q2: The inference speed charts on the T4 and Pixel 2 are only from exporting to TensorRT ?
A2: Yes. They are not trained on T4 and Pixel2. The inference speed is directly benchmarked on the hardwares.
