### ISSUE TITLE
Some simple questions

### ISSUE THREAD

**Issue by fly2tortoise** [idstcv/ZenNAS#12]
Dear researcher, Hello  
I ran into some problems while running the code that I couldn't solve when I wanted to test CIFAR10  
（python val_cifar.py --dataset cifar10 --gpu 0 --arch zennet_cifar10_model_size05M_res32）
![image](https://user-images.githubusercontent.com/85298331/149650246-542892b0-3677-42f8-90d7-03a60b32f025.png)

（**RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.**）
![image](https://user-images.githubusercontent.com/85298331/149650146-db99ae7d-2cea-42af-833e-9ba5702b1757.png)

The version I use is Torch1.7.1 Torchvision0.8.2 cudatoolkit10.2.89. May I ask if this is a problem with my operating environment?  Or do I need to make changes in the code?  Thanks a million, dear researcher.

**Comment by MingLin-home** [comment]
Hi fly2tortoise,

Thank you for the feedback! In your case, replace .view(-1) with .reshape(-1) should fix your problem. Please let me know if this workaround cannot address your problem.

**Comment by fly2tortoise** [comment]
Thank you very much. I will consult you if I have any details in the future, which has solved my big problem

**Comment by fly2tortoise** [comment]
Dear researcher, Hello
I have two more little questions to ask you about using this command (bash Zen_NAS_cifar_params1M. Sh) when I am searching on cifar10.
**I have a few questions:**
(1) I find that the search time is generally more than 12 hours. Is there something wrong with my method?
![image](https://user-images.githubusercontent.com/85298331/150636442-071ddaaa-7ddc-4f3e-a7de-22610758f6b0.png)


(2) At the beginning of the search, there are two errors (Fail to import Hvd. fail to import apex.)
![image](https://user-images.githubusercontent.com/85298331/150636451-2e8044e5-ca74-47fc-8b89-39d088b842de.png)


(3) My machine has 8 P100 cards, and I find that I only run on GPU0. Is there any way to make all 8 Gpus work together?

I'm sorry for my childish question, but I really hope you can help me with it.Thank you very much, distinguished researcher.
