### ISSUE TITLE
search problem

### ISSUE THREAD

**Issue by xmyyzy123** [idstcv/ZenNAS#13]
Hi, @MingLin-home 
   I search the zen-nas-1.0M in CIFAR10 by your default scripts, the result is that, params is less than 1M, but flops is 360M which is about twice as much as in the paper(160M). 
   Is this normal? How can I reproduce the level in the paper? Thank you.😄

**Comment by MingLin-home** [comment]
Hi xmyyzy123,
Thank you for the feedback!

The searching process is basically an EA algorithm, so there is some randomness. We do observe that when population is small, the EA will be stuck in local optimal structure. In that case, increasing the population size and longer evolution will usually improve the convergence.

In your feedback, it is normal if the params is slightly less than 1.0M. The FLOPs is however too large. Although we did not constrain the FLOPs, your 360M FLOPs usually indicates something wrong here. For example, did you set the resolution to be 32x32 when measuring FLOPs? You can train the network ( 1440 epochs with auto-augmentation suggested) to see the final accuracy. If it is much better than ours (as yours has larger FLOPs), it is  possible that your EA jumped out of the usual local optimal regimes. We only repeated our experiments a few times so do not be surprised if you find a better architecture.

**Comment by xmyyzy123** [comment]
Thanks for your reply.😀
