### ISSUE TITLE
File module missing

### ISSUE THREAD

**Issue by fly2tortoise** [idstcv/ZenNAS#14]
Dear researcher,
There was a file missing from the code (analyze_model.py) when I finished training the model. Always feel this module is very important. Could you help me find out what the problem is? Thank you very much
![image](https://user-images.githubusercontent.com/85298331/150684988-9130dc08-7805-4f9c-ba0f-6c96fbd708af.png)

![image](https://user-images.githubusercontent.com/85298331/150685192-b033e3bd-0447-43f2-aae8-9235b9830c2b.png)

**Comment by MingLin-home** [comment]
Hi fly2tortoise,

You need to install ptflops package:

pip install ptflops

Wish this helps.

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！
