### ISSUE TITLE
How does zen nas perform in detection tasks

### ISSUE THREAD

**Issue by Akon-Fiber** [idstcv/ZenNAS#18]
hi, lin, I am interesting your group work , do you do some expriments on object detect target ? 
I want to some nas work on object detect , zen-nas are attractive at speed, do you have some work or idea about this?

**Comment by MingLin-home** [comment]
Hi Akon-Fiber,
Thank you for your feedback!

We extend Zen-NAS to object detection. [Revisiting Efficient Object Detection Backbones from Zero-Shot Neural Architecture Search](https://openreview.net/forum?id=Fh_NyEuejsZ) Still under-review. Wish it helps!

Best Regards,
Ming
