### ISSUE TITLE
Does ZenScore Support MobileNet-like Search Space?

### ISSUE THREAD

**Issue by pprp** [idstcv/ZenNAS#21]
Thank you for your great work. 

I have tried zenscore and get great kendall tau in plain network. 

I wonder if zenscore can apply to MobileNet-like Search Space? 

Looking forward to your reply.

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！

**Comment by MingLin-home** [comment]
Hi pprp,

Yes, it support MobileNet search space. An examplar search space implementation is here:
https://github.com/idstcv/ZenNAS/blob/main/SearchSpace/search_space_IDW_fixfc.py

Also, please kindly check our most recent open source zero-cost NAS framework [Lightweight-NAS](https://github.com/alibaba/lightweight-neural-architecture-search). It is easier to use.

Best Regards,
Ming Lin
