### ISSUE TITLE
GENet how to use soft-labels

### ISSUE THREAD

**Issue by bigcash** [idstcv/ZenNAS#24]
i follow the paper "Neural Architecture Design for GPU-Efficient Networks", and see "We also use ResNet-152 as teacher network to get soft-labels. The soft-label loss and the true-label loss are weighted 1:1." at page 8
how to use soft-labels，teach genet. like knowledge distillation? have any code in this repo?

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！

**Comment by MingLin-home** [comment]
Hi Bigcash,
The code for knowledge distillation is here: 
[https://github.com/idstcv/ZenNAS/blob/main/ts_train_image_classification.py]()

**Comment by qq272574497** [comment]
Is it only suitable for VCNN network? Does the residual network fit?

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！

**Comment by qq272574497** [comment]
Can I communicate with you via email

**Comment by MingLin-home** [comment]
> Can I communicate with you via email

Sure, why not? We are open to all kinds of discussions and collaborations. Please send me email for something private. I will receive the notification email as well if you reply in this thread. So no difference except for privacy.
