### ISSUE TITLE
How to search in HardNet space?

### ISSUE THREAD

**Issue by 1chimaruGin** [idstcv/ZenNAS#26]
I'm new to NAS and I wonder how can I do searching in HardNet.

**Comment by MingLin-home** [comment]
We do not have built-in support for HardNet. You might need to implement the HardNet search space. Some examples are stored under "./SearchSpace/" folder.

**Comment by 1chimaruGin** [comment]
@MingLin-home , Thank for the response.

Sorry about unclear question. 
Did I need to create HardNet block or whole network in `./PlainNet/`?

Could you please provide me step by step procedure? :man-bowing:

**Comment by MingLin-home** [comment]
You can customize your network backbone in ./PlainNet. For example, you can create a new ./PlainNet/HardNet_SuperNet.py and implement Hardnet structure inside. The zen-score function does not care how supernet is internally implemented.

**Comment by 1chimaruGin** [comment]
Got it @MingLin-home . Thank you.
