### ISSUE TITLE
Is Attention Block in your search space?

### ISSUE THREAD

**Issue by dzk9528** [idstcv/ZenNAS#30]
Hi. I wonder if you have use attention blocks or transformer related architecture in your network because I did not see it in the code.

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！

**Comment by MingLin-home** [comment]
We did not support attention block currently.

**Comment by dzk9528** [comment]
Thanks for the reply~
