### ISSUE TITLE
能否请教一些关于MAE-DET的问题

### ISSUE THREAD

**Issue by marvellee1** [idstcv/ZenNAS#36]
计算方差以及得分的代码对应lightweight-neural-architecture-search/tinynas/scores中的那一个呢？计算特征图方差是通过模型前向推理数据得来的吗？还是将其转化到以计算通道的方式，和deepmad类似？

**Comment by dovedx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
邮件我已经成功接收，我会尽快处理并答复，谢谢！
