### ISSUE TITLE
Pre-trained model weights link is corrupted

### ISSUE THREAD

**Issue by maryanpetruk** [idstcv/ZenNAS#4]
The link you provided for zennet_imagenet1k_flops400M_SE_res224 model - https://idstcv.oss-cn-zhangjiakou.aliyuncs.com/les/iccv2021_zennet_imagenet1k_flops400M_SE_res224/student_best-params_rank0.pth is not working.

Please update the link in the readme

**Comment by MingLin-home** [comment]
Thank you so much! We have fixed the link address. To quick fix, replace "/les/" with "/pretrained_models/". It is a typo.
